# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

before_install:
  # execute all of the commands which need to be executed 
  # before installing dependencies
  - composer self-update
  - composer validate
  - composer install --prefer-dist 

script:
  # execute all of the commands which should make the build pass or fail
  - vendor/bin/phpunit
